[package]
name = "rubin-technote"
version = "0.1.0"
entrypoint = "src/lsstdoc.typ"
authors = ["Rubin Observatory"]
description = "Prototype Rubin Observatory technical document template"
compiler = "0.15.0"

[template]
path = "examples"
entrypoint = "technote.typ"
